// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { createTodo, deleteAttachment, deleteTodo, downloadAttachment, getAttachment, linkAttachment, listAttachmentsByResource, listTodos, type Options, unlinkAttachment, updateTodo, uploadAttachment } from '../sdk.gen';
import type { CreateTodoData, CreateTodoResponse, DeleteAttachmentData, DeleteAttachmentResponse, DeleteTodoData, DeleteTodoResponse, DownloadAttachmentData, DownloadAttachmentResponse, GetAttachmentData, GetAttachmentResponse, LinkAttachmentData, LinkAttachmentResponse, ListAttachmentsByResourceData, ListAttachmentsByResourceResponse, ListTodosData, ListTodosResponse, UnlinkAttachmentData, UnlinkAttachmentResponse, UpdateTodoData, UpdateTodoResponse, UploadAttachmentData, UploadAttachmentResponse } from '../types.gen';

/**
 * Upload attachment
 */
export const uploadAttachmentMutation = (options?: Partial<Options<UploadAttachmentData>>): UseMutationOptions<UploadAttachmentResponse, DefaultError, Options<UploadAttachmentData>> => {
    const mutationOptions: UseMutationOptions<UploadAttachmentResponse, DefaultError, Options<UploadAttachmentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await uploadAttachment({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete attachment
 */
export const deleteAttachmentMutation = (options?: Partial<Options<DeleteAttachmentData>>): UseMutationOptions<DeleteAttachmentResponse, DefaultError, Options<DeleteAttachmentData>> => {
    const mutationOptions: UseMutationOptions<DeleteAttachmentResponse, DefaultError, Options<DeleteAttachmentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteAttachment({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getAttachmentQueryKey = (options: Options<GetAttachmentData>) => createQueryKey('getAttachment', options);

/**
 * Get attachment metadata
 */
export const getAttachmentOptions = (options: Options<GetAttachmentData>) => queryOptions<GetAttachmentResponse, DefaultError, GetAttachmentResponse, ReturnType<typeof getAttachmentQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAttachment({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAttachmentQueryKey(options)
});

export const downloadAttachmentQueryKey = (options: Options<DownloadAttachmentData>) => createQueryKey('downloadAttachment', options);

/**
 * Download attachment content
 */
export const downloadAttachmentOptions = (options: Options<DownloadAttachmentData>) => queryOptions<DownloadAttachmentResponse, DefaultError, DownloadAttachmentResponse, ReturnType<typeof downloadAttachmentQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await downloadAttachment({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: downloadAttachmentQueryKey(options)
});

/**
 * Unlink attachment from a resource
 */
export const unlinkAttachmentMutation = (options?: Partial<Options<UnlinkAttachmentData>>): UseMutationOptions<UnlinkAttachmentResponse, DefaultError, Options<UnlinkAttachmentData>> => {
    const mutationOptions: UseMutationOptions<UnlinkAttachmentResponse, DefaultError, Options<UnlinkAttachmentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await unlinkAttachment({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Link attachment to a resource
 */
export const linkAttachmentMutation = (options?: Partial<Options<LinkAttachmentData>>): UseMutationOptions<LinkAttachmentResponse, DefaultError, Options<LinkAttachmentData>> => {
    const mutationOptions: UseMutationOptions<LinkAttachmentResponse, DefaultError, Options<LinkAttachmentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await linkAttachment({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listAttachmentsByResourceQueryKey = (options: Options<ListAttachmentsByResourceData>) => createQueryKey('listAttachmentsByResource', options);

/**
 * List attachments by resource
 */
export const listAttachmentsByResourceOptions = (options: Options<ListAttachmentsByResourceData>) => queryOptions<ListAttachmentsByResourceResponse, DefaultError, ListAttachmentsByResourceResponse, ReturnType<typeof listAttachmentsByResourceQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listAttachmentsByResource({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listAttachmentsByResourceQueryKey(options)
});

export const listTodosQueryKey = (options?: Options<ListTodosData>) => createQueryKey('listTodos', options);

/**
 * List TODO items for current user
 */
export const listTodosOptions = (options?: Options<ListTodosData>) => queryOptions<ListTodosResponse, DefaultError, ListTodosResponse, ReturnType<typeof listTodosQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listTodos({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listTodosQueryKey(options)
});

/**
 * Create a new TODO item
 */
export const createTodoMutation = (options?: Partial<Options<CreateTodoData>>): UseMutationOptions<CreateTodoResponse, DefaultError, Options<CreateTodoData>> => {
    const mutationOptions: UseMutationOptions<CreateTodoResponse, DefaultError, Options<CreateTodoData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createTodo({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete a TODO item
 */
export const deleteTodoMutation = (options?: Partial<Options<DeleteTodoData>>): UseMutationOptions<DeleteTodoResponse, DefaultError, Options<DeleteTodoData>> => {
    const mutationOptions: UseMutationOptions<DeleteTodoResponse, DefaultError, Options<DeleteTodoData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteTodo({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update a TODO item
 */
export const updateTodoMutation = (options?: Partial<Options<UpdateTodoData>>): UseMutationOptions<UpdateTodoResponse, DefaultError, Options<UpdateTodoData>> => {
    const mutationOptions: UseMutationOptions<UpdateTodoResponse, DefaultError, Options<UpdateTodoData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateTodo({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
