// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { createTodo, deleteTodo, listTodos, type Options, updateTodo } from '../sdk.gen';
import type { CreateTodoData, CreateTodoResponse, DeleteTodoData, DeleteTodoResponse, ListTodosData, ListTodosResponse, UpdateTodoData, UpdateTodoResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const listTodosQueryKey = (options?: Options<ListTodosData>) => createQueryKey('listTodos', options);

/**
 * List TODO items for current user
 */
export const listTodosOptions = (options?: Options<ListTodosData>) => queryOptions<ListTodosResponse, DefaultError, ListTodosResponse, ReturnType<typeof listTodosQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listTodos({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listTodosQueryKey(options)
});

/**
 * Create a new TODO item
 */
export const createTodoMutation = (options?: Partial<Options<CreateTodoData>>): UseMutationOptions<CreateTodoResponse, DefaultError, Options<CreateTodoData>> => {
    const mutationOptions: UseMutationOptions<CreateTodoResponse, DefaultError, Options<CreateTodoData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createTodo({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete a TODO item
 */
export const deleteTodoMutation = (options?: Partial<Options<DeleteTodoData>>): UseMutationOptions<DeleteTodoResponse, DefaultError, Options<DeleteTodoData>> => {
    const mutationOptions: UseMutationOptions<DeleteTodoResponse, DefaultError, Options<DeleteTodoData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteTodo({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update a TODO item
 */
export const updateTodoMutation = (options?: Partial<Options<UpdateTodoData>>): UseMutationOptions<UpdateTodoResponse, DefaultError, Options<UpdateTodoData>> => {
    const mutationOptions: UseMutationOptions<UpdateTodoResponse, DefaultError, Options<UpdateTodoData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateTodo({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
