// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { CreateTodoData, CreateTodoResponses, DeleteAttachmentData, DeleteAttachmentErrors, DeleteAttachmentResponses, DeleteTodoData, DeleteTodoErrors, DeleteTodoResponses, DeviceApproveData, DeviceApproveResponses, DeviceAuthorizeData, DeviceAuthorizeResponses, DeviceTokenData, DeviceTokenResponses, DeviceVerifyData, DeviceVerifyResponses, DownloadAttachmentData, DownloadAttachmentErrors, DownloadAttachmentResponses, GetAttachmentData, GetAttachmentErrors, GetAttachmentResponses, LinkAttachmentData, LinkAttachmentErrors, LinkAttachmentResponses, ListAttachmentsByResourceData, ListAttachmentsByResourceResponses, ListTodosData, ListTodosResponses, UnlinkAttachmentData, UnlinkAttachmentErrors, UnlinkAttachmentResponses, UpdateTodoData, UpdateTodoErrors, UpdateTodoResponses, UploadAttachmentData, UploadAttachmentResponses } from './types.gen';
import { zCreateTodoData, zDeleteAttachmentData, zDeleteTodoData, zDeviceApproveData, zDeviceAuthorizeData, zDeviceTokenData, zDeviceVerifyData, zDownloadAttachmentData, zGetAttachmentData, zLinkAttachmentData, zListAttachmentsByResourceData, zListTodosData, zUnlinkAttachmentData, zUpdateTodoData, zUploadAttachmentData } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Upload attachment
 */
export const uploadAttachment = <ThrowOnError extends boolean = false>(options: Options<UploadAttachmentData, ThrowOnError>) => (options.client ?? client).post<UploadAttachmentResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    requestValidator: async (data) => await zUploadAttachmentData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/attachments',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Delete attachment
 */
export const deleteAttachment = <ThrowOnError extends boolean = false>(options: Options<DeleteAttachmentData, ThrowOnError>) => (options.client ?? client).delete<DeleteAttachmentResponses, DeleteAttachmentErrors, ThrowOnError>({
    requestValidator: async (data) => await zDeleteAttachmentData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/attachments/{id}',
    ...options
});

/**
 * Get attachment metadata
 */
export const getAttachment = <ThrowOnError extends boolean = false>(options: Options<GetAttachmentData, ThrowOnError>) => (options.client ?? client).get<GetAttachmentResponses, GetAttachmentErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetAttachmentData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/attachments/{id}',
    ...options
});

/**
 * Download attachment content
 */
export const downloadAttachment = <ThrowOnError extends boolean = false>(options: Options<DownloadAttachmentData, ThrowOnError>) => (options.client ?? client).get<DownloadAttachmentResponses, DownloadAttachmentErrors, ThrowOnError>({
    requestValidator: async (data) => await zDownloadAttachmentData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/attachments/{id}/content',
    ...options
});

/**
 * Unlink attachment from a resource
 */
export const unlinkAttachment = <ThrowOnError extends boolean = false>(options: Options<UnlinkAttachmentData, ThrowOnError>) => (options.client ?? client).delete<UnlinkAttachmentResponses, UnlinkAttachmentErrors, ThrowOnError>({
    requestValidator: async (data) => await zUnlinkAttachmentData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/attachments/{id}/links',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Link attachment to a resource
 */
export const linkAttachment = <ThrowOnError extends boolean = false>(options: Options<LinkAttachmentData, ThrowOnError>) => (options.client ?? client).post<LinkAttachmentResponses, LinkAttachmentErrors, ThrowOnError>({
    requestValidator: async (data) => await zLinkAttachmentData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/attachments/{id}/links',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Approve device code
 */
export const deviceApprove = <ThrowOnError extends boolean = false>(options: Options<DeviceApproveData, ThrowOnError>) => (options.client ?? client).post<DeviceApproveResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zDeviceApproveData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/device/approve',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Start device code flow
 */
export const deviceAuthorize = <ThrowOnError extends boolean = false>(options: Options<DeviceAuthorizeData, ThrowOnError>) => (options.client ?? client).post<DeviceAuthorizeResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zDeviceAuthorizeData.parseAsync(data),
    url: '/auth/device/authorize',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Poll device code token
 */
export const deviceToken = <ThrowOnError extends boolean = false>(options: Options<DeviceTokenData, ThrowOnError>) => (options.client ?? client).post<DeviceTokenResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zDeviceTokenData.parseAsync(data),
    url: '/auth/device/token',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Device verification page
 */
export const deviceVerify = <ThrowOnError extends boolean = false>(options?: Options<DeviceVerifyData, ThrowOnError>) => (options?.client ?? client).get<DeviceVerifyResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zDeviceVerifyData.parseAsync(data),
    url: '/auth/device/verify',
    ...options
});

/**
 * List attachments by resource
 */
export const listAttachmentsByResource = <ThrowOnError extends boolean = false>(options: Options<ListAttachmentsByResourceData, ThrowOnError>) => (options.client ?? client).get<ListAttachmentsByResourceResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zListAttachmentsByResourceData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/resources/{resourceType}/{resourceId}/attachments',
    ...options
});

/**
 * List TODO items for current user
 */
export const listTodos = <ThrowOnError extends boolean = false>(options?: Options<ListTodosData, ThrowOnError>) => (options?.client ?? client).get<ListTodosResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zListTodosData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/todos',
    ...options
});

/**
 * Create a new TODO item
 */
export const createTodo = <ThrowOnError extends boolean = false>(options: Options<CreateTodoData, ThrowOnError>) => (options.client ?? client).post<CreateTodoResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zCreateTodoData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/todos',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a TODO item
 */
export const deleteTodo = <ThrowOnError extends boolean = false>(options: Options<DeleteTodoData, ThrowOnError>) => (options.client ?? client).delete<DeleteTodoResponses, DeleteTodoErrors, ThrowOnError>({
    requestValidator: async (data) => await zDeleteTodoData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/todos/{id}',
    ...options
});

/**
 * Update a TODO item
 */
export const updateTodo = <ThrowOnError extends boolean = false>(options: Options<UpdateTodoData, ThrowOnError>) => (options.client ?? client).patch<UpdateTodoResponses, UpdateTodoErrors, ThrowOnError>({
    requestValidator: async (data) => await zUpdateTodoData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/todos/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
