// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateTodoData, CreateTodoResponses, DeleteTodoData, DeleteTodoErrors, DeleteTodoResponses, ListTodosData, ListTodosResponses, UpdateTodoData, UpdateTodoErrors, UpdateTodoResponses } from './types.gen';
import { zCreateTodoData, zDeleteTodoData, zListTodosData, zUpdateTodoData } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List TODO items for current user
 */
export const listTodos = <ThrowOnError extends boolean = false>(options?: Options<ListTodosData, ThrowOnError>) => (options?.client ?? client).get<ListTodosResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zListTodosData.parseAsync(data),
    url: '/todos',
    ...options
});

/**
 * Create a new TODO item
 */
export const createTodo = <ThrowOnError extends boolean = false>(options: Options<CreateTodoData, ThrowOnError>) => (options.client ?? client).post<CreateTodoResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zCreateTodoData.parseAsync(data),
    url: '/todos',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a TODO item
 */
export const deleteTodo = <ThrowOnError extends boolean = false>(options: Options<DeleteTodoData, ThrowOnError>) => (options.client ?? client).delete<DeleteTodoResponses, DeleteTodoErrors, ThrowOnError>({
    requestValidator: async (data) => await zDeleteTodoData.parseAsync(data),
    url: '/todos/{id}',
    ...options
});

/**
 * Update a TODO item
 */
export const updateTodo = <ThrowOnError extends boolean = false>(options: Options<UpdateTodoData, ThrowOnError>) => (options.client ?? client).patch<UpdateTodoResponses, UpdateTodoErrors, ThrowOnError>({
    requestValidator: async (data) => await zUpdateTodoData.parseAsync(data),
    url: '/todos/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
