// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/v1` | (string & {});
};

export type TodoItem = {
    id: string;
    title: string;
    done: boolean;
    bucket: 'later' | 'week' | 'today';
    createdAt: string;
};

export type CreateTodoRequest = {
    title: string;
};

export type UpdateTodoRequest = {
    title?: string;
    done?: boolean;
    bucket?: 'later' | 'week' | 'today';
};

export type ListTodosData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/todos';
};

export type ListTodosResponses = {
    /**
     * List of TODO items
     */
    200: Array<TodoItem>;
};

export type ListTodosResponse = ListTodosResponses[keyof ListTodosResponses];

export type CreateTodoData = {
    body: CreateTodoRequest;
    path?: never;
    query?: never;
    url: '/todos';
};

export type CreateTodoResponses = {
    /**
     * Created TODO item
     */
    201: TodoItem;
};

export type CreateTodoResponse = CreateTodoResponses[keyof CreateTodoResponses];

export type DeleteTodoData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/todos/{id}';
};

export type DeleteTodoErrors = {
    /**
     * TODO item not found
     */
    404: unknown;
};

export type DeleteTodoResponses = {
    /**
     * TODO item deleted
     */
    204: void;
};

export type DeleteTodoResponse = DeleteTodoResponses[keyof DeleteTodoResponses];

export type UpdateTodoData = {
    body: UpdateTodoRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/todos/{id}';
};

export type UpdateTodoErrors = {
    /**
     * TODO item not found
     */
    404: unknown;
};

export type UpdateTodoResponses = {
    /**
     * Updated TODO item
     */
    200: TodoItem;
};

export type UpdateTodoResponse = UpdateTodoResponses[keyof UpdateTodoResponses];
