// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:2910/api/v1' | `${string}://${string}/api/v1` | (string & {});
};

export type Attachment = {
    contentType: string;
    createdAt: string;
    downloadUrl: string;
    filename: string;
    id: string;
    sizeBytes: number;
};

export type Counter = {
    count: number;
};

export type CreateMemoRequest = {
    content: MemoContent;
    excerpt: string;
    plainText: string;
    references: Array<string>;
    tags: Array<string>;
};

export type CreateTodoRequest = {
    title: string;
};

export type DeviceApproveRequest = {
    userCode: string;
};

export type DeviceApproveResult = {
    status: string;
};

export type DeviceAuthorizeRequest = {
    clientId: string;
    deviceName?: string;
    scope?: string;
};

export type DeviceAuthorizeResult = {
    deviceCode: string;
    expiresIn: number;
    interval: number;
    userCode: string;
    verificationUri: string;
    verificationUriComplete: string;
};

export type DeviceTokenRequest = {
    deviceCode: string;
};

export type DeviceTokenResult = {
    accessToken?: string;
    error?: string;
    errorDescription?: string;
    refreshToken?: string;
    tokenType?: string;
};

export type LinkAttachmentRequest = {
    resourceId: string;
    resourceType: string;
};

export type Memo = {
    archivedAt?: string | null;
    content: MemoContent;
    createdAt: string;
    excerpt: string;
    id: string;
    plainText: string;
    references: Array<string>;
    state: MemoState;
    tags: Array<string>;
    updatedAt: string;
};

export type MemoContent = {
    [key: string]: unknown;
};

export type MemoState = 'active' | 'archived';

export type MemoSummary = {
    archivedAt?: string | null;
    createdAt: string;
    excerpt: string;
    id: string;
    plainText: string;
    state: MemoState;
    tags: Array<string>;
    updatedAt: string;
};

export type TagSummary = {
    count: number;
    name: string;
};

export type TodoItem = {
    bucket: 'later' | 'week' | 'today';
    createdAt: string;
    description: string;
    done: boolean;
    doneAt?: string | null;
    id: string;
    title: string;
};

export type UpdateMemoRequest = {
    content: MemoContent;
    excerpt: string;
    plainText: string;
    references: Array<string>;
    state?: MemoState;
    tags: Array<string>;
};

export type UpdateTodoRequest = {
    bucket?: 'later' | 'week' | 'today';
    description?: string;
    done?: boolean;
    title?: string;
};

export type UploadAttachmentData = {
    body: {
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/attachments';
};

export type UploadAttachmentResponses = {
    /**
     * Attachment uploaded
     */
    201: Attachment;
};

export type UploadAttachmentResponse = UploadAttachmentResponses[keyof UploadAttachmentResponses];

export type DeleteAttachmentData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/attachments/{id}';
};

export type DeleteAttachmentErrors = {
    /**
     * Attachment not found
     */
    404: unknown;
};

export type DeleteAttachmentResponses = {
    /**
     * Attachment deleted
     */
    204: void;
};

export type DeleteAttachmentResponse = DeleteAttachmentResponses[keyof DeleteAttachmentResponses];

export type GetAttachmentData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/attachments/{id}';
};

export type GetAttachmentErrors = {
    /**
     * Attachment not found
     */
    404: unknown;
};

export type GetAttachmentResponses = {
    /**
     * Attachment metadata
     */
    200: Attachment;
};

export type GetAttachmentResponse = GetAttachmentResponses[keyof GetAttachmentResponses];

export type DownloadAttachmentData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/attachments/{id}/content';
};

export type DownloadAttachmentErrors = {
    /**
     * Attachment not found
     */
    404: unknown;
};

export type DownloadAttachmentResponses = {
    /**
     * Attachment content
     */
    200: Blob | File;
};

export type DownloadAttachmentResponse = DownloadAttachmentResponses[keyof DownloadAttachmentResponses];

export type UnlinkAttachmentData = {
    body: LinkAttachmentRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/attachments/{id}/links';
};

export type UnlinkAttachmentErrors = {
    /**
     * Attachment not found
     */
    404: unknown;
};

export type UnlinkAttachmentResponses = {
    /**
     * Attachment unlinked
     */
    204: void;
};

export type UnlinkAttachmentResponse = UnlinkAttachmentResponses[keyof UnlinkAttachmentResponses];

export type LinkAttachmentData = {
    body: LinkAttachmentRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/attachments/{id}/links';
};

export type LinkAttachmentErrors = {
    /**
     * Attachment not found
     */
    404: unknown;
};

export type LinkAttachmentResponses = {
    /**
     * Attachment linked
     */
    204: void;
};

export type LinkAttachmentResponse = LinkAttachmentResponses[keyof LinkAttachmentResponses];

export type DeviceApproveData = {
    body: DeviceApproveRequest;
    path?: never;
    query?: never;
    url: '/auth/device/approve';
};

export type DeviceApproveResponses = {
    /**
     * Approved
     */
    200: DeviceApproveResult;
};

export type DeviceApproveResponse = DeviceApproveResponses[keyof DeviceApproveResponses];

export type DeviceAuthorizeData = {
    body: DeviceAuthorizeRequest;
    path?: never;
    query?: never;
    url: '/auth/device/authorize';
};

export type DeviceAuthorizeResponses = {
    /**
     * Device code issued
     */
    200: DeviceAuthorizeResult;
};

export type DeviceAuthorizeResponse = DeviceAuthorizeResponses[keyof DeviceAuthorizeResponses];

export type DeviceTokenData = {
    body: DeviceTokenRequest;
    path?: never;
    query?: never;
    url: '/auth/device/token';
};

export type DeviceTokenResponses = {
    /**
     * Device token polling result
     */
    200: DeviceTokenResult;
};

export type DeviceTokenResponse = DeviceTokenResponses[keyof DeviceTokenResponses];

export type DeviceVerifyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/device/verify';
};

export type DeviceVerifyResponses = {
    /**
     * Verification page
     */
    200: string;
};

export type DeviceVerifyResponse = DeviceVerifyResponses[keyof DeviceVerifyResponses];

export type ListAttachmentsByResourceData = {
    body?: never;
    path: {
        resourceType: string;
        resourceId: string;
    };
    query?: never;
    url: '/resources/{resourceType}/{resourceId}/attachments';
};

export type ListAttachmentsByResourceResponses = {
    /**
     * Attachment list
     */
    200: Array<Attachment>;
};

export type ListAttachmentsByResourceResponse = ListAttachmentsByResourceResponses[keyof ListAttachmentsByResourceResponses];

export type ListTodosData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/todos';
};

export type ListTodosResponses = {
    /**
     * List of TODO items
     */
    200: Array<TodoItem>;
};

export type ListTodosResponse = ListTodosResponses[keyof ListTodosResponses];

export type CreateTodoData = {
    body: CreateTodoRequest;
    path?: never;
    query?: never;
    url: '/todos';
};

export type CreateTodoResponses = {
    /**
     * Created TODO item
     */
    201: TodoItem;
};

export type CreateTodoResponse = CreateTodoResponses[keyof CreateTodoResponses];

export type DeleteTodoData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/todos/{id}';
};

export type DeleteTodoErrors = {
    /**
     * TODO item not found
     */
    404: unknown;
};

export type DeleteTodoResponses = {
    /**
     * TODO item deleted
     */
    204: void;
};

export type DeleteTodoResponse = DeleteTodoResponses[keyof DeleteTodoResponses];

export type UpdateTodoData = {
    body: UpdateTodoRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/todos/{id}';
};

export type UpdateTodoErrors = {
    /**
     * TODO item not found
     */
    404: unknown;
};

export type UpdateTodoResponses = {
    /**
     * Updated TODO item
     */
    200: TodoItem;
};

export type UpdateTodoResponse = UpdateTodoResponses[keyof UpdateTodoResponses];
