// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:2910/api/v1' | `${string}://${string}/api/v1` | (string & {});
};

export type Attachment = {
    contentType: string;
    createdAt: string;
    downloadUrl: string;
    filename: string;
    id: string;
    sizeBytes: number;
};

export type CreateTodoRequest = {
    title: string;
};

export type LinkAttachmentRequest = {
    resourceId: string;
    resourceType: string;
};

export type TodoItem = {
    bucket: 'later' | 'week' | 'today';
    createdAt: string;
    description: string;
    done: boolean;
    doneAt?: string | null;
    id: string;
    title: string;
};

export type UpdateTodoRequest = {
    bucket?: 'later' | 'week' | 'today';
    description?: string;
    done?: boolean;
    title?: string;
};

export type UploadAttachmentData = {
    body: {
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/attachments';
};

export type UploadAttachmentResponses = {
    /**
     * Attachment uploaded
     */
    201: Attachment;
};

export type UploadAttachmentResponse = UploadAttachmentResponses[keyof UploadAttachmentResponses];

export type DeleteAttachmentData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/attachments/{id}';
};

export type DeleteAttachmentErrors = {
    /**
     * Attachment not found
     */
    404: unknown;
};

export type DeleteAttachmentResponses = {
    /**
     * Attachment deleted
     */
    204: void;
};

export type DeleteAttachmentResponse = DeleteAttachmentResponses[keyof DeleteAttachmentResponses];

export type GetAttachmentData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/attachments/{id}';
};

export type GetAttachmentErrors = {
    /**
     * Attachment not found
     */
    404: unknown;
};

export type GetAttachmentResponses = {
    /**
     * Attachment metadata
     */
    200: Attachment;
};

export type GetAttachmentResponse = GetAttachmentResponses[keyof GetAttachmentResponses];

export type DownloadAttachmentData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/attachments/{id}/content';
};

export type DownloadAttachmentErrors = {
    /**
     * Attachment not found
     */
    404: unknown;
};

export type DownloadAttachmentResponses = {
    /**
     * Attachment content
     */
    200: Blob | File;
};

export type DownloadAttachmentResponse = DownloadAttachmentResponses[keyof DownloadAttachmentResponses];

export type UnlinkAttachmentData = {
    body: LinkAttachmentRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/attachments/{id}/links';
};

export type UnlinkAttachmentErrors = {
    /**
     * Attachment not found
     */
    404: unknown;
};

export type UnlinkAttachmentResponses = {
    /**
     * Attachment unlinked
     */
    204: void;
};

export type UnlinkAttachmentResponse = UnlinkAttachmentResponses[keyof UnlinkAttachmentResponses];

export type LinkAttachmentData = {
    body: LinkAttachmentRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/attachments/{id}/links';
};

export type LinkAttachmentErrors = {
    /**
     * Attachment not found
     */
    404: unknown;
};

export type LinkAttachmentResponses = {
    /**
     * Attachment linked
     */
    204: void;
};

export type LinkAttachmentResponse = LinkAttachmentResponses[keyof LinkAttachmentResponses];

export type ListAttachmentsByResourceData = {
    body?: never;
    path: {
        resourceType: string;
        resourceId: string;
    };
    query?: never;
    url: '/resources/{resourceType}/{resourceId}/attachments';
};

export type ListAttachmentsByResourceResponses = {
    /**
     * Attachment list
     */
    200: Array<Attachment>;
};

export type ListAttachmentsByResourceResponse = ListAttachmentsByResourceResponses[keyof ListAttachmentsByResourceResponses];

export type ListTodosData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/todos';
};

export type ListTodosResponses = {
    /**
     * List of TODO items
     */
    200: Array<TodoItem>;
};

export type ListTodosResponse = ListTodosResponses[keyof ListTodosResponses];

export type CreateTodoData = {
    body: CreateTodoRequest;
    path?: never;
    query?: never;
    url: '/todos';
};

export type CreateTodoResponses = {
    /**
     * Created TODO item
     */
    201: TodoItem;
};

export type CreateTodoResponse = CreateTodoResponses[keyof CreateTodoResponses];

export type DeleteTodoData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/todos/{id}';
};

export type DeleteTodoErrors = {
    /**
     * TODO item not found
     */
    404: unknown;
};

export type DeleteTodoResponses = {
    /**
     * TODO item deleted
     */
    204: void;
};

export type DeleteTodoResponse = DeleteTodoResponses[keyof DeleteTodoResponses];

export type UpdateTodoData = {
    body: UpdateTodoRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/todos/{id}';
};

export type UpdateTodoErrors = {
    /**
     * TODO item not found
     */
    404: unknown;
};

export type UpdateTodoResponses = {
    /**
     * Updated TODO item
     */
    200: TodoItem;
};

export type UpdateTodoResponse = UpdateTodoResponses[keyof UpdateTodoResponses];
