// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zCreateTodoRequest = z.object({
    title: z.string()
});

export const zTodoItem = z.object({
    bucket: z.enum([
        'later',
        'week',
        'today'
    ]),
    createdAt: z.iso.datetime(),
    done: z.boolean(),
    id: z.uuid(),
    title: z.string()
});

export const zUpdateTodoRequest = z.object({
    bucket: z.enum([
        'later',
        'week',
        'today'
    ]).optional(),
    done: z.boolean().optional(),
    title: z.string().optional()
});

export const zListTodosData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zCreateTodoData = z.object({
    body: zCreateTodoRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zDeleteTodoData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.uuid()
    }),
    query: z.never().optional()
});

export const zUpdateTodoData = z.object({
    body: zUpdateTodoRequest,
    path: z.object({
        id: z.uuid()
    }),
    query: z.never().optional()
});
